"""empty message

Revision ID: a789c2a216ee
Revises: 7c7c24584bf2
Create Date: 2025-07-10 19:34:06.049636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a789c2a216ee'
down_revision: Union[str, Sequence[str], None] = '7c7c24584bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_activated')
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activated')
    op.add_column('chats', sa.Column('is_activated', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False))
    # ### end Alembic commands ###
